-- Supabase SQL script for creating the failed_logins table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS failed_logins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: Create an index on username and timestamp for faster querying
CREATE INDEX IF NOT EXISTS idx_failed_logins_username_time 
ON failed_logins(username, timestamp);
